
select = ["E", "F", "B"]

exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "migrations",
]

line-length = 119

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py312"